### PR TITLE
Profile Addition: Parthiv Kapoor

### PR DESCRIPTION
**Pull request by parthivkapoor0101**
## Check List (Check all the applicable boxes) 

- [x] My Changes follow the Code of Conduct of this Project. 
- [x] My Post or Change does not contain any **Plagarized** Content. 
- [x] The title of the PR is a short description of the Changes made.

### CODE REVIEW

**Comment by Zemerik** [comment]
Thank you for opening this PR. 

It looks like your profile image isn't loading correctly. Do you have any other image or link you would like to try?

Regards, 
Zemerik

**Review by Zemerik — CHANGES_REQUESTED** [review]
If you need any assistance, feel free to let me know!

**Comment by Zemerik** [comment]
Unfortunately, your image still isn't loading. Follow the steps below to fix this:

1. Upload your desired picture to github as your Profile Picture
2. Copy the address of the image on your github profile

**Comment by parthivkapoor0101** [comment]
try now

**Review by Zemerik — APPROVED** [review]
Thank you for Contributing to ZemProfiles! Feel free to check out [ZemPosts](https://github.com/Zemerik/ZemPosts) & [ZemShowcase](https://github.com/Zemerik/ZemShowcase)!

**Pull request merged**
